/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Demo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8555970184175360301L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Demo\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":[\"int\",\"null\"]},{\"name\":\"dataList\",\"type\":{\"type\":\"array\",\"items\":\"long\"}},{\"name\":\"dataMap\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Integer age;
  @Deprecated public java.util.List<java.lang.Long> dataList;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> dataMap;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Demo() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param age The new value for age
   * @param dataList The new value for dataList
   * @param dataMap The new value for dataMap
   */
  public Demo(java.lang.CharSequence name, java.lang.Integer age, java.util.List<java.lang.Long> dataList, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> dataMap) {
    this.name = name;
    this.age = age;
    this.dataList = dataList;
    this.dataMap = dataMap;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return age;
    case 2: return dataList;
    case 3: return dataMap;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    case 2: dataList = (java.util.List<java.lang.Long>)value$; break;
    case 3: dataMap = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'dataList' field.
   * @return The value of the 'dataList' field.
   */
  public java.util.List<java.lang.Long> getDataList() {
    return dataList;
  }

  /**
   * Sets the value of the 'dataList' field.
   * @param value the value to set.
   */
  public void setDataList(java.util.List<java.lang.Long> value) {
    this.dataList = value;
  }

  /**
   * Gets the value of the 'dataMap' field.
   * @return The value of the 'dataMap' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getDataMap() {
    return dataMap;
  }

  /**
   * Sets the value of the 'dataMap' field.
   * @param value the value to set.
   */
  public void setDataMap(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.dataMap = value;
  }

  /**
   * Creates a new Demo RecordBuilder.
   * @return A new Demo RecordBuilder
   */
  public static avro.Demo.Builder newBuilder() {
    return new avro.Demo.Builder();
  }

  /**
   * Creates a new Demo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Demo RecordBuilder
   */
  public static avro.Demo.Builder newBuilder(avro.Demo.Builder other) {
    return new avro.Demo.Builder(other);
  }

  /**
   * Creates a new Demo RecordBuilder by copying an existing Demo instance.
   * @param other The existing instance to copy.
   * @return A new Demo RecordBuilder
   */
  public static avro.Demo.Builder newBuilder(avro.Demo other) {
    return new avro.Demo.Builder(other);
  }

  /**
   * RecordBuilder for Demo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Demo>
    implements org.apache.avro.data.RecordBuilder<Demo> {

    private java.lang.CharSequence name;
    private java.lang.Integer age;
    private java.util.List<java.lang.Long> dataList;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> dataMap;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.Demo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dataList)) {
        this.dataList = data().deepCopy(fields()[2].schema(), other.dataList);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dataMap)) {
        this.dataMap = data().deepCopy(fields()[3].schema(), other.dataMap);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Demo instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.Demo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dataList)) {
        this.dataList = data().deepCopy(fields()[2].schema(), other.dataList);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dataMap)) {
        this.dataMap = data().deepCopy(fields()[3].schema(), other.dataMap);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public avro.Demo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public avro.Demo.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public avro.Demo.Builder setAge(java.lang.Integer value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public avro.Demo.Builder clearAge() {
      age = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataList' field.
      * @return The value.
      */
    public java.util.List<java.lang.Long> getDataList() {
      return dataList;
    }

    /**
      * Sets the value of the 'dataList' field.
      * @param value The value of 'dataList'.
      * @return This builder.
      */
    public avro.Demo.Builder setDataList(java.util.List<java.lang.Long> value) {
      validate(fields()[2], value);
      this.dataList = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dataList' field has been set.
      * @return True if the 'dataList' field has been set, false otherwise.
      */
    public boolean hasDataList() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dataList' field.
      * @return This builder.
      */
    public avro.Demo.Builder clearDataList() {
      dataList = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataMap' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getDataMap() {
      return dataMap;
    }

    /**
      * Sets the value of the 'dataMap' field.
      * @param value The value of 'dataMap'.
      * @return This builder.
      */
    public avro.Demo.Builder setDataMap(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.dataMap = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dataMap' field has been set.
      * @return True if the 'dataMap' field has been set, false otherwise.
      */
    public boolean hasDataMap() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dataMap' field.
      * @return This builder.
      */
    public avro.Demo.Builder clearDataMap() {
      dataMap = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Demo build() {
      try {
        Demo record = new Demo();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        record.dataList = fieldSetFlags()[2] ? this.dataList : (java.util.List<java.lang.Long>) defaultValue(fields()[2]);
        record.dataMap = fieldSetFlags()[3] ? this.dataMap : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
