/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface ExampleService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ExampleService\",\"namespace\":\"avro\",\"types\":[{\"type\":\"enum\",\"name\":\"Suit\",\"symbols\":[\"SPADES\",\"DIAMONDS\",\"CLUBS\",\"HEARTS\"]},{\"type\":\"record\",\"name\":\"DataExample\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"success\",\"type\":\"boolean\"},{\"name\":\"suit\",\"type\":\"Suit\"},{\"name\":\"addressList\",\"type\":{\"type\":\"array\",\"items\":\"string\",\"javaclass\":\"java.util.ArrayList\"}},{\"name\":\"demoMap\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}],\"messages\":{\"sayHello\":{\"request\":[{\"name\":\"content\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"DataExample\"}],\"response\":\"null\"}}}");
  /**
   */
  java.lang.Void sayHello(java.lang.CharSequence content, avro.DataExample data) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ExampleService {
    public static final org.apache.avro.Protocol PROTOCOL = avro.ExampleService.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sayHello(java.lang.CharSequence content, avro.DataExample data, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}